### GET /
GET http://localhost:2121/

### Register a user POST /AUTH/REGISTER
POST http://localhost:2121/auth/register
Content-Type: application/json

{
    "username": "abc@gmail.com",
     "password": "123"
}
### login a user to: /auth/login
POST http://localhost:2121/auth/login
Content-Type: application/json

{
    "username": "abc@gmail.com",
     "password": "123"
}

###fetch all todo's, protected
GET http://localhost:2121/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0MjYzMDk3LCJleHAiOjE3MzQzNDk0OTd9.GXFDvfqLx4x1wQ2uCfqnYsre7WMqxrfqrXEGKzUtEw0

### add a todo
POST http://localhost:2121/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0MjYzMDk3LCJleHAiOjE3MzQzNDk0OTd9.GXFDvfqLx4x1wQ2uCfqnYsre7WMqxrfqrXEGKzUtEw0
Content-Type: application/json

{
    "task": "2nd task",
     "completed": 1
}
### update a todo

PUT http://localhost:2121/todos/3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0MjYzMDk3LCJleHAiOjE3MzQzNDk0OTd9.GXFDvfqLx4x1wQ2uCfqnYsre7WMqxrfqrXEGKzUtEw0
Content-Type: application/json

{
    "completed":1
}
### delete a todo
DELETE http://localhost:2121/todos/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0MjYzMDk3LCJleHAiOjE3MzQzNDk0OTd9.GXFDvfqLx4x1wQ2uCfqnYsre7WMqxrfqrXEGKzUtEw0
# Content-Type: application/json